export const COUNTRY_LIST = [
    { label:'Argentina', cityName: 'Buenos Aires', value:"AR" },
    { label: 'Brazil', cityName: 'Sao Paulo', value:"BR" },
    { label:'España', cityName: 'Barcelona', value:"ES" },
    { label:'Venezuela', cityName: 'Caracas', value:"VE" },
    { label:'Colombia', cityName: 'Medellin', value:"CO" },
    { label:'Estados Unidos', cityName: 'Miami', value:"US" },
    { label:'Alemania', cityName: 'Berlin', value:"DE" },
    { label:'India', cityName: 'Mumbai', value:"IN" },
    { label:'Rusia', cityName: 'Moscow', value:"RU" },
    { label:'Australia', cityName: 'Sydney', value:"AU" },
    { label:'China', cityName: 'Beijing', value:"CN" },
    { label:'Mexico', cityName: 'Guadalajara', value:"MX" },
    { label:'Bolivia', cityName: 'La Paz', value:"BO" },
    { label:'Portugal', cityName: 'Lisbon', value:"PT" },
    { label:'Peru', cityName: 'Lima', value:"PE" },
    { label:'Chile', cityName: 'Santiago', value:"CL" },
]